### ISSUE TITLE
Server Start Error Message 1.18.1 habitat 1.1.1

### ISSUE THREAD

**Issue by Tyronadre** [SnappyDragon18/Bloom-and-Gloom#11]
(not crashing but an error): 
Unable to locate field TYPE_BY_STATE (TYPE_BY_STATE) on type net.minecraft.world.entity.ai.village.poi.PoiType
net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: TYPE_BY_STATE
        at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:241) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.util.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:86) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at mod.schnappdragon.habitat.core.misc.HabitatPOI.addBeehivePOI(HabitatPOI.java:14) ~[habitat-1.1.1.jar%23100!:1.1.1]
        at mod.schnappdragon.habitat.core.Habitat.lambda$commonSetup$0(Habitat.java:69) ~[habitat-1.1.1.jar%23100!:1.1.1]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$1(DeferredWorkQueue.java:81) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:77) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:71) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
        at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:71) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.core.ParallelTransition.lambda$finalActivityGenerator$2(ParallelTransition.java:51) ~[forge-1.18.1-39.0.10-universal.jar%23176!:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:215) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:183) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:183) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:47) ~[forge-1.18.1-39.0.10-universal.jar%23176!:?]
        at net.minecraft.server.Main.main(Main.java:104) ~[server-1.18.1-20211210.034407-srg.jar%23172!:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.10.jar%2323!:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
Caused by: java.lang.NoSuchFieldException: TYPE_BY_STATE
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:235) ~[fmlcore-1.18.1-39.0.10.jar%23173!:?]
        ... 36 more

**Comment by SnappyDragon64** [comment]
Will look into it soon
